spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: username
    password: password
  batch:
    job:
      names: ${job.name:NONE}
logging:
  level:
    org.springframework.batch: debug
